site_name: "Platform Engineering Copilot"
site_description: Documentation for Platform Engineering Copilot
repo_url: https://github.com/POps-Rox/platform-engineering-copilot
edit_uri: edit/main/docs/

nav:
  - Home: index.md

plugins:
  - techdocs-core

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
